// src/Immediate.Jobs.Dashboard/DashboardClient/src/components/JobTable.vue
<script setup lang="ts">
import { Eye, Layers3, RotateCcw, Trash2 } from '@lucide/vue';

import FeedbackState from '@/components/FeedbackState.vue';
import StateBadge from '@/components/StateBadge.vue';
import { canRetryJob, type JobRecord } from '@/contracts';
import { formatDate } from '@/format';

withDefaults(defineProps<{
	rows: JobRecord[];
	busyJobId?: string;
}>(), {
	busyJobId: undefined,
});

const emit = defineEmits<{
	select: [job: JobRecord];
	openBatch: [batchId: string];
	retry: [job: JobRecord];
	delete: [job: JobRecord];
}>();

function retryLabel(job: JobRecord): string {
	return job.state === 'Scheduled' ? `Run ${job.jobName} now` : `Retry ${job.jobName}`;
}
</script>

<template>
	<div class="table-card">
		<FeedbackState v-if="rows.length === 0" title="Nothing to show yet" description="Jobs will appear here as they are scheduled." />
		<div v-else class="table-scroll">
			<table>
				<thead>
					<tr>
						<th>Job</th>
						<th>Queue</th>
						<th>Group</th>
						<th>Batch</th>
						<th>State</th>
						<th>Attempt</th>
						<th>Due</th>
						<th>Completed</th>
						<th><span class="sr-only">Actions</span></th>
					</tr>
				</thead>
				<tbody>
					<tr v-for="job in rows" :key="job.id" :data-job-id="job.id">
						<td>
							<button
								class="table-link max-w-72 truncate"
								type="button"
								:title="job.jobName"
								@click="emit('select', job)"
							>
								{{ job.jobName }}
							</button>
						</td>
						<td><code>{{ job.queueName }}</code></td>
						<td>
							<code v-if="job.groupId !== null" class="block max-w-48 truncate" :title="job.groupId">{{ job.groupId }}</code>
							<span v-else class="text-muted">—</span>
						</td>
						<td>
							<button v-if="job.batchId" class="table-link" type="button" @click="emit('openBatch', job.batchId)">
								<Layers3 :size="13" aria-hidden="true" />
								{{ job.batchId }}
							</button>
							<span v-else class="text-muted">—</span>
						</td>
						<td><StateBadge :state="job.state" /></td>
						<td class="numeric">{{ job.attempt }}</td>
						<td>{{ formatDate(job.dueAt) }}</td>
						<td>{{ formatDate(job.completedAt) }}</td>
						<td>
							<div class="row-actions">
								<button
									class="icon-button"
									type="button"
									:aria-label="`View ${job.jobName}`"
									@click="emit('select', job)"
								>
									<Eye :size="15" aria-hidden="true" />
								</button>
								<button
									v-if="canRetryJob(job)"
									class="icon-button"
									type="button"
									:disabled="busyJobId === job.id"
									:aria-label="retryLabel(job)"
									@click="emit('retry', job)"
								>
									<RotateCcw :size="15" aria-hidden="true" />
								</button>
								<button
									v-if="job.state === 'Failed'"
									class="icon-button danger"
									type="button"
									:disabled="busyJobId === job.id"
									:aria-label="`Delete ${job.jobName}`"
									@click="emit('delete', job)"
								>
									<Trash2 :size="15" aria-hidden="true" />
								</button>
							</div>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</template>

// src/Immediate.Jobs.Dashboard/DashboardClient/src/JobTable.svelte
<script>
  let {
    rows = [],
    act,
    selected,
    select,
    selectBatch = () => {}
  } = $props();

  function fmt(value) {
    return value ? new Date(value).toLocaleString() : '—';
  }

  function pretty(value) {
    try {
      return JSON.stringify(JSON.parse(value), null, 2);
    } catch {
      return value;
    }
  }

  function isSelected(job) {
    return selected?.id === job.id;
  }

  function toggleDetails(job) {
    select(isSelected(job) ? null : job);
  }
</script>

<div class="table-wrap">
  {#if rows.length === 0}
    <div class="empty">Nothing to show yet.</div>
  {:else}
    <table>
      <thead>
        <tr>
          <th>Job</th>
          <th>Queue</th>
          <th>Batch</th>
          <th>State</th>
          <th>Attempt</th>
          <th>Due</th>
          <th>Completed</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {#each rows as job}
          <tr>
            <td>
              <button
                class="job-link"
                aria-expanded={isSelected(job)}
                onclick={() => toggleDetails(job)}
              >
                {job.jobName}
              </button>
            </td>
            <td><code>{job.queueName}</code></td>
            <td>
              {#if job.batchId}
                <button class="job-link" onclick={() => selectBatch(job.batchId)}>
                  {job.batchId}
                </button>
              {:else}
                <span class="muted">—</span>
              {/if}
            </td>
            <td>
              <span class="state {job.state.toLowerCase()}">{job.state}</span>
            </td>
            <td>{job.attempt}</td>
            <td>{fmt(job.dueAt)}</td>
            <td>{fmt(job.completedAt)}</td>
            <td>
              <span class="actions">
                <button
                  class="action"
                  aria-expanded={isSelected(job)}
                  onclick={() => toggleDetails(job)}
                >
                  {isSelected(job) ? 'Hide' : 'Details'}
                </button>
                {#if job.state === 'Failed'}
                  <button
                    class="action"
                    onclick={() => act(`jobs/${encodeURIComponent(job.id)}/retry`)}
                  >
                    Retry
                  </button>
                  <button
                    class="action danger"
                    onclick={() => act(`jobs/${encodeURIComponent(job.id)}`, 'DELETE')}
                  >
                    Delete
                  </button>
                {/if}
              </span>
            </td>
          </tr>
          {#if isSelected(job)}
            <tr class="job-detail">
              <td colspan="8">
                <section class="detail" aria-label={`Details for ${job.jobName}`}>
                  <div class="section-title">
                    <h2>{job.jobName}</h2>
                    <button class="action" onclick={() => select(null)}>Close</button>
                  </div>
                  <dl>
                    <div>
                      <dt>Invocation</dt>
                      <dd><code>{job.id}</code></dd>
                    </div>
                    <div>
                      <dt>Queue</dt>
                      <dd><code>{job.queueName}</code></dd>
                    </div>
                    <div>
                      <dt>Batch</dt>
                      <dd>
                        {#if job.batchId}
                          <button class="job-link" onclick={() => selectBatch(job.batchId)}>
                            {job.batchId}
                          </button>
                        {:else}
                          —
                        {/if}
                      </dd>
                    </div>
                    <div>
                      <dt>State</dt>
                      <dd>
                        <span class="state {job.state.toLowerCase()}">{job.state}</span>
                      </dd>
                    </div>
                    <div>
                      <dt>Attempt</dt>
                      <dd>{job.attempt}</dd>
                    </div>
                    <div>
                      <dt>Created</dt>
                      <dd>{fmt(job.createdAt)}</dd>
                    </div>
                    <div>
                      <dt>Due</dt>
                      <dd>{fmt(job.dueAt)}</dd>
                    </div>
                    <div>
                      <dt>Completed</dt>
                      <dd>{fmt(job.completedAt)}</dd>
                    </div>
                  </dl>
                  <h3>Payload</h3>
                  <pre>{pretty(job.payload)}</pre>
                  {#if job.context}
                    <h3>Context envelope</h3>
                    <pre>{pretty(job.context)}</pre>
                  {/if}
                  {#if job.lastError}
                    <h3>Latest error</h3>
                    <pre class="failure">{job.lastError}</pre>
                  {/if}
                </section>
              </td>
            </tr>
          {/if}
        {/each}
      </tbody>
    </table>
  {/if}
</div>
